### ISSUE TITLE
White screen on boot

### ISSUE THREAD

**Issue by teletonn** [luke-r-mills/ESPIR_Crypto_Ticker#19]
Hello! Want to thank you for your very cool work. But I have a little problem, I've installed needed versions of everything, compiled and flashed my Wemos D1 Mini, the screen and IR connected as in your D1 to D6 pins. All I can see is only white screen and no boot or something. When I push buttons on IR remote, I see that led on wemos and on IR is blinking, and thats everything that happens, no messages in serial monitor too. How can I fix it? I'm really want to make such cool device. Thanks.

**Comment by lr-m** [comment]
Hi! Glad the code is getting some use :) 

You got me at quite a good time, I had a D1 mini lying around so wired it up to test it and seems to be working alright, so there are a couple of things I think it could be:
- In the board manager, did you select "LOLIN(WEMOS) D1 mini lite"?

![image](https://github.com/lr-m/ESPIR-Crypto-Ticker/assets/47477832/94621c92-52a9-4cbb-9177-73a04b32db84)

- Are your connections solid? Breadboards can tend to have awful connections after a while
- You are definitely using an ST7735 display (should be on the back of the module)

Here is a picture of my setup, connections are the same as the diagram (minus the IR LED as it isn't on a board, but by your description that doesn't seem to be a problem as its flashing)

![20240504_181144](https://github.com/lr-m/ESPIR-Crypto-Ticker/assets/47477832/fd539f7a-cb46-4755-8aa3-5d8071674780)

Let me know if you get it working, happy to look at how you've got it set up :)

**Comment by teletonn** [comment]
Thanks for quick answer. I've tried with Wemos D1 R2 & mini before, after your answered I've tried select Wemos D1 Mini Lite, but result is the same. Here is my setup. I'm plan to 3d-print some case, if it will work, I'll post the result then )

![WhatsApp Image 2024-05-05 at 20 42 17](https://github.com/lr-m/ESPIR-Crypto-Ticker/assets/37016713/1b419897-f1e1-4abe-9ecf-5d8b65fc8554)
![WhatsApp Image 2024-05-05 at 20 42 16 (1)](https://github.com/lr-m/ESPIR-Crypto-Ticker/assets/37016713/8a9cdeb5-6547-4e2d-83ee-a0753f480e02)
![WhatsApp Image 2024-05-05 at 20 42 16](https://github.com/lr-m/ESPIR-Crypto-Ticker/assets/37016713/7437471a-4472-487c-8b4a-caa01d5d74cc)

**Comment by teletonn** [comment]
Yes! Finally I found it! it was bad connection on LCD there was bad soldier on SCL. I've repair it and now it works! Thanks again for help and for your brilliant code! ;)

**Comment by teletonn** [comment]
![WhatsApp Image 2024-05-05 at 22 05 59](https://github.com/lr-m/ESPIR-Crypto-Ticker/assets/37016713/78f697aa-1dd8-46a5-9ac5-e5972a534905)

**Comment by lr-m** [comment]
Glad its working! :)
